# Site settings
title: Snowy Epistles
description: >
  Currently on attempt #25 on escaping winter...
permalink: /:title

# Build settings
markdown: kramdown
future: true

defaults:
    -
        scope:
            path: ""
        values:
            layout: page
